# these direcotory will be used by the code
directories:
  # rdf directory
  rdf_directory : ./RDF/Meerterns/
  #directory for sparql anything
  query_dir :  ./sparql_anything
  # sparql anything query for converting jams to rdf
  query_test_file : ./sparql_anything/jams_ontology_pattern.sparql
  #temporary file - deleted during query execution
  query_current_file : ./sparql_anything/current.rq
  #SPARQL anything engine file, this is used to execute sparql query for JAMS conversion
  sparql_anything_jar_file : ./sparql_anything/sa.jar
settings:
  #corpus collection
  jams_collection: Meerterns
  #choco namespace
  namespace : http://purl.org/choco/data/
